denoising_step_list: [1000, 750, 500, 250]
warp_denoising_step: true
num_frame_per_block: 3
model_name: Wan2.1-T2V-1.3B
group_id: 11
model_kwargs:
  local_attn_size: 12
  timestep_shift: 5.0
  sink_size: 1
  memory_size: 6
  recent_exclude: 5
  use_latentmem: true
  compression_method: avg_pool
  ae_ckpt: /data/zxl/LongLive-RAG-assets/models/LongLive-RAG/checkpoints/ae_latent_mem.pt
  retrieval_backend: draftmap_online
  group_runtime_mode: baseline
  group_sparse_ratio: 0.0
generator_ckpt: /data/zxl/LongLive-RAG-assets/models/LongLive-RAG/checkpoints/longlive_base.pt
lora_ckpt: /data/zxl/LongLive-RAG-assets/models/LongLive-RAG/checkpoints/longlive_lora.pt
adapter: {type: lora, rank: 256, alpha: 256, dropout: 0.0, dtype: bfloat16, verbose: false}
data_path: /data/zxl/LongLive-RAG-profile/prompts10.txt
output_folder: /data/zxl/LongLive-RAG-group11_15_h200/results/group11_case01
inference_iter: 0
skip_existing: false
num_output_frames: 120
use_ema: false
seed: 0
num_samples: 1
save_with_index: true
global_sink: true
context_noise: 0
