denoising_step_list: [1000, 750, 500, 250]
warp_denoising_step: true
num_frame_per_block: 3
model_name: Wan2.1-T2V-1.3B
model_kwargs:
  local_attn_size: 6
  timestep_shift: 5.0
  sink_size: 1
  memory_size: 6
  recent_exclude: 5
  use_latentmem: true
  history_kv_storage: k_int8_v_fp8
generator_ckpt: checkpoints/longlive_base.pt
lora_ckpt: checkpoints/longlive_lora.pt
adapter: {type: lora, rank: 256, alpha: 256, dropout: 0.0, dtype: bfloat16, verbose: false}
data_path: /home/zju/work/zxl/LongLive-RAG-profile/prompts10.txt
output_folder: /home/zju/work/zxl/anemoi_native_draftattention_5090/results/persistent_kint8_vfp8_w6
metrics_dir: /home/zju/work/zxl/anemoi_native_draftattention_5090/results/persistent_kint8_vfp8_w6/metrics
inference_iter: -1
skip_existing: false
num_output_frames: 120
use_ema: false
seed: 0
num_samples: 1
save_with_index: true
global_sink: true
context_noise: 0
