import csv, json
from pathlib import Path

root = Path('/data/zxl/LongLive-RAG-group11_15_h200')
csv_path = root / 'results/native_w6_w12_case01_profile.csv'
json_path = root / 'results/native_w6_w12_case01_profile.json'
old_audit_json = root / 'results/native_old70_vs_new40_timer_audit.json'
old_audit_md = root / 'reports/native_old70_vs_new40_timer_audit.md'
out_json = root / 'results/native_w6_w12_profile_field_mapping_audit.json'
out_md = root / 'reports/native_w6_w12_profile_field_mapping_audit.md'

rows = list(csv.DictReader(csv_path.open()))
mapping = []
for r in rows:
    e2e = float(r['e2e_latency_s'])
    transformer = float(r['transformer_latency_s'])
    wrapper = float(r['self_attention_wrapper_s'])
    kernel = float(r['attention_kernel_s'])
    mapping.append({
        'window': int(r['window']),
        'E2E_INFERENCE_S': e2e,
        'TRANSFORMER_S': transformer,
        'SELF_ATTN_WRAPPER_S': wrapper,
        'NON_TRANSFORMER_E2E_S': e2e - transformer,
        'ATTENTION_KERNEL_S': kernel,
        'self_attention_source': f"results/native_w6_w12_case01_profile/w{r['window']}_v2/native_case01_profile.json:self_attention_wrapper_s",
        'self_attention_source_code': 'profiling_configs/native_case01_profiler_v3.py:44; sum(host_s) over CausalWanSelfAttention.forward wrappers',
        'non_transformer_source_expression': 'E2E_INFERENCE_S - TRANSFORMER_S',
        'non_transformer_source_code': 'results/native_w6_w12_case01_profile.csv derived mapping; not a direct profiler component timer',
    })

audit = {
    'WRAPPER_MISLABEL_CONFIRMED': 'YES',
    'OTHER_FIELD_MAPPING_ERRORS_FOUND': 'NO',
    'authoritative_rows': mapping,
    'answers': {
        '12.669_and_12.823': 'NON_TRANSFORMER_E2E_S = E2E_INFERENCE_S - TRANSFORMER_S; derived residuals, not self-attention wrapper measurements',
        'authoritative_self_attention_wrapper': 'The raw native_case01_profile.json field self_attention_wrapper_s, produced by host timing around each CausalWanSelfAttention.forward',
        'later_report_status': 'The later timer audit report mislabeled the derived residual as Wrapper',
        'other_errors': 'No other mapping error found in the inspected native CSV/JSON/report and old-vs-new audit artifacts. NOT_AVAILABLE fields remain unavailable, not zero.',
    },
    'inspected_files': [str(csv_path), str(json_path), str(old_audit_json), str(old_audit_md), str(root / 'profiling_configs/native_case01_profiler_v3.py')],
}
out_json.write_text(json.dumps(audit, indent=2) + '\n')

# Keep raw profile outputs untouched; correct only the derived audit JSON/report.
old = json.loads(old_audit_json.read_text())
for row in old.get('new_values', {}).values():
    if isinstance(row, dict) and 'wrapper' in row:
        row['non_transformer_e2e'] = row.pop('wrapper')
old['FIELD_MAPPING_CORRECTION'] = 'The former new_values.wrapper labels are corrected to new_values.non_transformer_e2e. Raw profile self_attention_wrapper_s is unchanged.'
old_audit_json.write_text(json.dumps(old, indent=2) + '\n')

text = old_audit_md.read_text()
text = text.replace('| Window | E2E s | Transformer s | Wrapper s | Attention kernel s | E2E - Transformer s |', '| Window | E2E s | Transformer s | Self-attention wrapper s | Attention kernel s | NON_TRANSFORMER_E2E_S |')
text = text.replace('| 6 | 40.435522 | 27.766429 | 12.669093 | 6.185424 | 12.669093 |', '| 6 | 40.435522 | 27.766429 | 14.990465 | 6.185424 | 12.669093 |')
text = text.replace('| 12 | 43.004939 | 30.181653 | 12.823285 | 10.659426 | 12.823285 |', '| 12 | 43.004939 | 30.181653 | 17.479825 | 10.659426 | 12.823285 |')
text += '\n## Field-mapping correction\n\nThe former `Wrapper s` column was mislabeled. Values 12.669093 s (W6) and 12.823286 s (W12) are derived `NON_TRANSFORMER_E2E_S = E2E_INFERENCE_S - TRANSFORMER_S`. The authoritative self-attention wrapper measurements remain 14.990465 s and 17.479825 s, from `native_case01_profile.json:self_attention_wrapper_s`, generated by `native_case01_profiler_v3.py:44`. No raw profile values were changed.\n'
old_audit_md.write_text(text)

md = '''# Native W6/W12 profile field-mapping audit

## Conclusion

`WRAPPER_MISLABEL_CONFIRMED = YES` for the later old-vs-new timer audit
report. The values 12.669093 s and 12.823286 s are not self-attention
wrapper times. They are derived residuals:

`NON_TRANSFORMER_E2E_S = E2E_INFERENCE_S - TRANSFORMER_S`

The raw profiling outputs already contain the correct self-attention wrapper
field and were not modified.

## Authoritative mapping

| Window | E2E_INFERENCE_S | TRANSFORMER_S | SELF_ATTN_WRAPPER_S | NON_TRANSFORMER_E2E_S | ATTENTION_KERNEL_S |
|---:|---:|---:|---:|---:|---:|
| W6 | 40.435522 | 27.766429 | 14.990465 | 12.669093 | 6.185424 |
| W12 | 43.004939 | 30.181653 | 17.479825 | 12.823286 | 10.659426 |

## Field origins

- `E2E_INFERENCE_S` and `TRANSFORMER_S`: runtime metadata fields aggregated
  into `results/native_w6_w12_case01_profile.csv`.
- `SELF_ATTN_WRAPPER_S`: raw
  `results/native_w6_w12_case01_profile/w{6,12}_v2/native_case01_profile.json`,
  field `self_attention_wrapper_s`.
- Wrapper source: `profiling_configs/native_case01_profiler_v3.py:44`,
  `sum(x['host_s'] for x in forward_rows)`, where `host_s` is measured around
  `CausalWanSelfAttention.forward`.
- `ATTENTION_KERNEL_S`: raw profile field `attention_kernel_s`, accumulated
  from CUDA event pairs around the attention call.
- `NON_TRANSFORMER_E2E_S`: derived only as `E2E - Transformer`; it is not a
  direct profiler component timer.

## Corrections

The later `native_old70_vs_new40_timer_audit.md` and JSON had labeled the
derived residual as `Wrapper`. That label has been corrected to
`NON_TRANSFORMER_E2E_S`, while retaining the measured raw wrapper values.

No other field-mapping error was found in the inspected CSV, JSON, raw profile,
and audit artifacts. `NOT_AVAILABLE` remains distinct from zero; no residual
has been promoted to a measured component.

## Required answers

1. 12.669093 s and 12.823286 s are non-transformer E2E residuals.
2. Authoritative self-attention wrapper times are 14.990465 s and 17.479825 s.
3. Yes, the later audit report was mislabeled.
4. No additional mapping error affecting Group11 comparison was found.
'''
out_md.write_text(md)
print(out_json)
print(out_md)
